Specifying trusted clients in a config file
achirkin/qua-kit pull request #50
Opened 2017-08-03 10:12 UTC by NorfairKing

2017-08-15 09:08 UTC, achirkin requested changes
`luci-connect` is fine (apart from that I would ask you to document top-level exported functions).

In `helen`, I added several comments regarding config files.
Have not checked `qua-server` part yet.

2017-08-15 09:08 UTC, achirkin commented on apps/hs/helen/src/Helen/Core/Types.hs
> +      portstr <- (tclo .: "port")
Don't clients connect using the same port all the time?
So far, helen specifies the port she listens to, and all clients just connect to this port from various ip addresses.
Therefore, I think there is no point to keep both, port and host, for each client in JSON/yaml configuration.
Maybe, let's just keep them as a list of strings? (each string is an ip address).

2017-08-15 09:08 UTC, achirkin commented on apps/hs/helen/src/Helen/Core.hs
> +      putStrLn $ unlines
Do you mean `HelenWorld` cannot be initialized before you run `readConfigFromYamlFile`, and that is the reason you don't use MonadLogger here?

2017-08-15 09:08 UTC, achirkin commented on apps/hs/helen/src/Helen/Core.hs
> +        _ -> die $ "Failed to parse ip address from " <> cs
Please, let's avoid halting program if there is any single chance to continue somehow with the error message sent to log :) Failing to parse ip address is not so big deal :)

2017-08-17 08:44 UTC, NorfairKing commented on apps/hs/helen/src/Helen/Core.hs
> +      putStrLn $ unlines
That's right.

2017-08-17 08:44 UTC, NorfairKing commented on apps/hs/helen/src/Helen/Core.hs
> +        _ -> die $ "Failed to parse ip address from " <> cs
Okido!

2017-08-17 08:44 UTC, NorfairKing commented on apps/hs/helen/src/Helen/Core/Types.hs
> +      portstr <- (tclo .: "port")
Also fixed. We'll be keeping an 'IP' instead of a string.

2017-08-21 09:38 UTC, merged